wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685478426.836012
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 86
      2:
      - 1
      - 11
      - 49
      - 55
      - 86
      3:
      - 13
      - 23
      4: 3.11.3
      5: 0.15.3
      6: 4.28.1
      8:
      - 4
      - 5
